# Generated by Django 4.2.4 on 2023-09-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskbar', '0005_tasks_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
