# Generated by Django 4.2.4 on 2023-11-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskbar', '0008_proyecto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='imagen',
        ),
    ]
